mode: debug
mysql:
  dsn: >-
    ${lime_MYSQL_USERNAME}:${lime_MYSQL_PASSWORD}@tcp(${lime_MYSQL_HOST}:${lime_MYSQL_PORT})/${lime_MYSQL_DB}?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
redis:
  host: ${lime_REDIS_HOST}:${lime_REDIS_PORT}
  auth: ${lime_REDIS_PASSWORD}
  pool:
    min: 3
    max: 20
mongo:
  host: ${lime_MONGO_HOST}
  port: ${lime_MONGO_PORT}
  db: ${lime_MONGO_DB}
  username: ${lime_MONGO_USERNAME}
  password: ${lime_MONGO_PASSWORD}
  authSource: ${lime_MONGO_AUTHSOURCE}
cors:
  allow_credentials: false
  allow_headers:
    - '*'
  allow_methods:
    - GET
    - POST
    - OPTIONS
    - PUT
    - DELETE
  allow_origins:
    - '*'
  enable: false
  max_age: 7200
upload:
  image_prefix_url: "http://127.0.0.1:8000"
  image_save_path: "data/images/"
  image_max_size: 5
  image_allow_exts:
    - .jpg
    - .jpeg
    - .png"
auth:
  access_secret: ""
  refresh_secret: ""
qiniu:
  ak: ""
  sk: ""
  bucket: ""