mode: debug
mysql:
  dsn: >-
    root:root@tcp(172.72.33.11:3306)/lime?charset=utf8&parseTime=True&loc=Local
  pool:
    min: 5
    max: 20
redis:
  host: 127.0.0.1:6379
  auth:
  pool:
    min: 3
    max: 20
mongo:
  host: ${LIME_MONGO_HOST}
  port: ${LIME_MONGO_PORT}
  db: ${LIME_MONGO_DB}
  username: ${LIME_MONGO_USERNAME}
  password: ${LIME_MONGO_PASSWORD}
  authSource: ${LIME_MONGO_AUTHSOURCE}